### PR TITLE
Make clear style configurable

### PR DESCRIPTION
**Pull request by Blaok**
## Purpose

Make it possible to use `gitmux` in other environments. In my case, I'm using it in `zsh` prompt.

## Approach

Add a `Clear` field to the `Styles` struct.

I know this is not the intended usage so feel free to reject the PR. In any case, thank you for this awesome tool!

### CODE REVIEW

**Review by arl — APPROVED** [review]
Thanks for doing that.
Can you just modify the rest of the tests so that all use `StyleClear` as value of the `Clear` field.

**Comment by Blaok** [comment]
> Can you just modify the rest of the tests so that all use `StyleClear` as value of the `Clear` field.

Done!

**Review by arl — APPROVED** [review]
Thanks

**Comment by arl** [comment]
Forgot to ask you if you could update the code block with the default config as YAML in the readme with the new field: https://github.com/arl/gitmux#customizing
@Blaok

**Pull request merged**
