### PR TITLE
feat: separate layout items with spaces

### LINKED ISSUE #90: [FEATURE] Conditional Spacing
**Is your feature request related to a problem? Please describe.**
I would like to conditionally load spaces in my layout based off what data is avaliable.

**Describe the solution you'd like**
I'd like spaces to be rendered conditionally based on if it's needed to show clear spacing.

**Describe alternatives you've considered**
I've thought about prepending spaces on the symbols, but it's creates a separate set of problems with spacing.

**Additional context**
Without spaces, you'll notice the different sections bump up against each other.
Screenshot 2023-03-07 at 5 35 15 PM

 If I do include `' '` space values in my layout and the different sections shown I end up with unwanted whitespace.
Screenshot 2023-03-07 at 5 35 33 PM

### PR DESCRIPTION
**Pull request by joshmedeski**
Fixes #90

## Purpose

Adds a space at the end of every layout component.

## Approach

- Properly adds a space, after every layout component.
- Update the default layout to not include a forward space on the dash separator.

### CODE REVIEW

**Comment by joshmedeski** [comment]
Sure thing!

**Comment by joshmedeski** [comment]
The way the tests are written make it hard to debug. I recommend moving away from a for loop for tests so when a test fails you get immediate feedback and a proper line number for what test failed.

**Comment by arl** [comment]
Each test in the for loop is a sub test. You can run a single sub test with `go test -run TEST NAME/SUBTESTNAME`

**Comment by joshmedeski** [comment]
I'm wondering if this should be a flag that doesn't cause a breaking change to the way everything is rendered now? (like `tailing_spaces`?)

Let me know your thoughts.

**Comment by arl** [comment]
> I'm wondering if this should be a flag that doesn't cause a breaking change to the way everything is rendered now? (like `tailing_spaces`?)
> 
> Let me know your thoughts.

Yep this might be needed if the change is too important. Let me think about it

**Comment by joshmedeski** [comment]
I got the tests working and I got the feature working to the best of my ability for now.

But if someone doesn't like having the trailing spaces between each layout component we'll have to write more code to handle that.

**Comment by arl** [comment]
> Adds a space at the end of every layout component.
@joshmedeski 

What's the difference between adding spaces manually in the `layout` section?

For example, this is the default `layout` section:

```yaml
layout: [branch, remote-branch, divergence, "- ", flags]
```

This is the one I've been using:
```yaml
layout: [branch, ' ', remote-branch, divergence, ' - ', flags, ' ', stats]
```

**Comment by joshmedeski** [comment]
So in your second example, when divergence, flags, and / or stats have nothing to show. You end up with extra white spaces in the tmux status bar (see the screenshots from the issue). I'd rather trim the whitespace if there's nothing to render.

**Comment by arl** [comment]
@joshmedeski I've tagged a new release with both your pull-requests (v0.10.0)
Thanks again for the help!

**Comment by joshmedeski** [comment]
That makes more sense. This was my first time in the codebase so I'm starting to get my way around.

I had the same idea later on to move this logic in the place that chains the layout components together, thanks for doing it!

**Comment by arl** [comment]
Sure, no worries. You did a great job 🎉

**Comment by joshmedeski** [comment]
Can we update to make sure the final component includes a space if anything is rendered?

Screenshot 2023-03-22 at 9 54 39 AM

**Comment by arl** [comment]
> Can we update to make sure the final component includes a space if anything is rendered?
> 
> Screenshot 2023-03-22 at 9 54 39 AM

I don't understand. Do you mean a trailing space?

**Comment by joshmedeski** [comment]
Exactly

**Comment by arl** [comment]
Ah i think I got it. I think you mean a trailing space, in case anything was rendered. That's a particular case though. Majority of people, myself included, do not have anything after gitmux status shown on their tmux status bar.
Isn't that something you can fix by adding a trailing space to your config `layout`?

**Comment by joshmedeski** [comment]
Fair point, so my tmux status is `{session_name} {gitmux} {windows}`. But sometimes I load tmux sessions that don't have a gitmux session so I'm hoping to have `{session_name} {windows}` render without any extra spaces.

It's a little tricky. Maybe I can add a `trailing_space` option to support this situation? Just adding a space at the end of my layout potentially creates two spaces when I was hoping for just one on tmux sessions that don't render anything in gitmux.

Hope all that makes sense.

**Comment by joshmedeski** [comment]
I implemented the feature, see #94 

This is a non-breaking change but is very useful for people who want to place gitmux between other elements in their tmux status bar. Hopefully you find it not too invasive and decide to merge it.

**Pull request merged**
